// Maps a raw ingredient photo URL to its transparent-background cutout PNG.
// Source photos live at /assets/pizza/<group>/<name>.jpg (white background);
// cutouts (white removed) live at /assets/pizza/cutouts/<group>/<name>.png.
// Generated by scripts/generate-cutouts.cjs — full-colour food, no blend tricks.
export function cutoutUrl(imageUrl: string): string {
  return imageUrl
    .replace("/assets/pizza/", "/assets/pizza/cutouts/")
    .replace(/\.jpe?g$/i, ".png");
}
